services:
  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080